In [1]:
import numpy as np
import pandas as pd

In [2]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={"a":10,"b":20,"c":30}
my_list
d

{'a': 10, 'b': 20, 'c': 30}

In [4]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [11]:
ser1=pd.Series([1,2,3,4],index=["USA","Germany","USSR","Japan"])
ser2=pd.Series([1,2,3,4],index=["USA","Germany","Italy","Japan"])

In [12]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [13]:
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [14]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [15]:
ser1['USA']

np.int64(1)

In [23]:
from numpy.random import randn
np.random.seed(200)

In [24]:
df=pd.DataFrame(randn(5,4),index="A B C D E".split(),columns="W X Y Z".split())

In [25]:
df

          W         X         Y         Z
A -1.450948  1.910953  0.711879 -0.247738
B  0.361466 -0.032950 -0.221347  0.477257
C -0.691939  0.792006  0.073249  1.303286
D  0.213481  1.017349  1.911712 -0.529672
E  1.842135 -1.057235 -0.862916  0.237631

In [26]:
df['W']

A   -1.450948
B    0.361466
C   -0.691939
D    0.213481
E    1.842135
Name: W, dtype: float64

In [27]:
df['new']=df['W']+df['Y']

In [28]:
df

          W         X         Y         Z       new
A -1.450948  1.910953  0.711879 -0.247738 -0.739069
B  0.361466 -0.032950 -0.221347  0.477257  0.140120
C -0.691939  0.792006  0.073249  1.303286 -0.618690
D  0.213481  1.017349  1.911712 -0.529672  2.125193
E  1.842135 -1.057235 -0.862916  0.237631  0.979219

In [30]:
df.drop('new',axis=1,inplace=True)

In [31]:
df

          W         X         Y         Z
A -1.450948  1.910953  0.711879 -0.247738
B  0.361466 -0.032950 -0.221347  0.477257
C -0.691939  0.792006  0.073249  1.303286
D  0.213481  1.017349  1.911712 -0.529672
E  1.842135 -1.057235 -0.862916  0.237631

In [32]:
df.drop("E",axis=0)

          W         X         Y         Z
A -1.450948  1.910953  0.711879 -0.247738
B  0.361466 -0.032950 -0.221347  0.477257
C -0.691939  0.792006  0.073249  1.303286
D  0.213481  1.017349  1.911712 -0.529672

In [33]:
df.loc['A']

W   -1.450948
X    1.910953
Y    0.711879
Z   -0.247738
Name: A, dtype: float64

In [37]:
df.iloc[2]

W   -0.691939
X    0.792006
Y    0.073249
Z    1.303286
Name: C, dtype: float64

In [35]:
df.loc["B","Y"]

np.float64(-0.2213467176273389)

In [36]:
df.loc[['A','B'],['W','Y']]

          W         Y
A -1.450948  0.711879
B  0.361466 -0.221347

In [38]:
df

          W         X         Y         Z
A -1.450948  1.910953  0.711879 -0.247738
B  0.361466 -0.032950 -0.221347  0.477257
C -0.691939  0.792006  0.073249  1.303286
D  0.213481  1.017349  1.911712 -0.529672
E  1.842135 -1.057235 -0.862916  0.237631

In [39]:
df>0

       W      X      Y      Z
A  False   True   True  False
B   True  False  False   True
C  False   True   True   True
D   True   True   True  False
E   True  False  False   True

In [45]:
df[df>0]

          W         X         Y         Z
A       NaN  1.910953  0.711879       NaN
B  0.361466       NaN       NaN  0.477257
C       NaN  0.792006  0.073249  1.303286
D  0.213481  1.017349  1.911712       NaN
E  1.842135       NaN       NaN  0.237631

In [46]:
df[df['W']>0]

          W         X         Y         Z
B  0.361466 -0.032950 -0.221347  0.477257
D  0.213481  1.017349  1.911712 -0.529672
E  1.842135 -1.057235 -0.862916  0.237631

In [47]:
df[df['W']>0]['Y']

B   -0.221347
D    1.911712
E   -0.862916
Name: Y, dtype: float64

In [49]:
df[df['W']>0][['Y','X']]

          Y         X
B -0.221347 -0.032950
D  1.911712  1.017349
E -0.862916 -1.057235

In [50]:
df[(df['W']>0)&(df['Y']>1)]

          W         X         Y         Z
D  0.213481  1.017349  1.911712 -0.529672

In [51]:
mdf=pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [52]:
mdf

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [53]:
mdf.dropna()

     A    B  C
0  1.0  5.0  1

In [54]:
mdf.dropna(axis=1)

   C
0  1
1  2
2  3

In [55]:
mdf.fillna(value='FILL VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [56]:
mdf.fillna(value=mdf.mean())

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [59]:
data={"Company":['GOOG','GOOG','MSFT','MSFT','FB','FB'],
      "Person":['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
      'Sales':[200,120,340,124,243,350]}

In [60]:
df1=pd.DataFrame(data)

In [61]:
df1

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [62]:
df1.describe

<bound method NDFrame.describe of   Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350>

In [63]:
df1.columns

Index(['Company', 'Person', 'Sales'], dtype='object')

In [64]:
df1.Company.unique()

array(['GOOG', 'MSFT', 'FB'], dtype=object)

In [65]:
by_comp=df1.groupby('Company')

In [ ]:
by_comp

In [ ]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [68]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [69]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [70]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [71]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [73]:
by_comp.std(numeric_only=True)

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [74]:
by_comp.mean(numeric_only=True)

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [76]:
by_comp.min(numeric_only=True)

         Sales
Company
FB         243
GOOG       120
MSFT       124

In [3]:
left = pd.DataFrame({"key": ["K0", "K1", "K2", "K3"],
                    "A": ["A0", "A1", "A2", "A3"],
                    "B": ["B0", "B1", "B2", "B3"]})
right = pd.DataFrame({"key": ["K0", "K1", "K2", "K3"],
                      "C": ["C0", "C1", "C2", "C3"],
                      "D": ["D0", "D1", "D2", "D3"],})
result = pd.merge(left, right, on="key")
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [4]:
left1=pd.DataFrame({'A':['A0','A1','A2'],
                    'B':['B0','B1','B2']},
                    index=['K0','K1','K2'])
right1=pd.DataFrame({'C':['C0','C1','C2'],
                    'D':['D0','D1','D2']},
                    index=['K0','K2','K3'])

In [5]:
left1.join(right1)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

In [6]:
right1.join(left1)

     C   D    A    B
K0  C0  D0   A0   B0
K2  C1  D1   A2   B2
K3  C2  D2  NaN  NaN

In [7]:
left1.join(right1,how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C1   D1
K3  NaN  NaN   C2   D2

In [8]:
sal=pd.read_csv("G:\\Projects\\Code\\EXTRA\\DATA\\Salaries (1).csv")

In [9]:
sal

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [10]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [11]:
sal.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [12]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [13]:
sal['BasePay'].mean()

np.float64(66325.44884048769)

In [14]:
sal['OvertimePay'].max()

np.float64(245131.88)

In [16]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [18]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]['EmployeeName']
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [20]:
sal['JobTitle'].nunique()

2159

In [21]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [26]:
sal['title_len']=sal['JobTitle'].apply(len)

In [27]:
sal[['title_len','TotalPayBenefits']].corr()

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

In [31]:
#print no' of jobs with chief
c=0
jobs=sal['JobTitle']
for i in jobs:
    if "chief" in i.lower():
        c+=1
print(c)

627

In [32]:
def name_find(a,name):
    if a.lower() in name.lower():
        return True
    else:
        return False
sum(sal['JobTitle'].apply(lambda x: name_find("Chief",x)))

627