In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df=pd.read_csv("C:\\Users\\cl601_07\\Documents\\24070127070\\Dataset\\4_movie_scores.csv")

In [4]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   first_name        4 non-null      object
 1   last_name         4 non-null      object
 2   age               4 non-null      float64
 3   Gender            4 non-null      object
 4   pre_movie_score   3 non-null      float64
 5   post_movie_score  3 non-null      float64
dtypes: float64(3), object(3)
memory usage: 368.0+ bytes

In [6]:
df.isnull()

   first_name  last_name    age  Gender  pre_movie_score  post_movie_score
0       False      False  False   False            False             False
1        True       True   True    True             True              True
2       False      False  False   False             True              True
3       False      False  False   False            False             False
4       False      False  False   False            False             False

In [7]:
df.notnull()

   first_name  last_name    age  Gender  pre_movie_score  post_movie_score
0        True       True   True    True             True              True
1       False      False  False   False            False             False
2        True       True   True    True            False             False
3        True       True   True    True             True              True
4        True       True   True    True             True              True

In [8]:
df.columns

Index(['first_name', 'last_name', 'age', 'Gender', 'pre_movie_score',
       'post_movie_score'],
      dtype='object')

In [9]:
df['first_name']

0     Root
1      NaN
2    Stark
3    Sofie
4     Emma
Name: first_name, dtype: object

In [10]:
df['first_name'].notnull()

0     True
1    False
2     True
3     True
4     True
Name: first_name, dtype: bool

In [11]:
df[df['first_name'].notnull()]

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [12]:
df['pre_movie_score'].isnull()

0    False
1     True
2     True
3    False
4    False
Name: pre_movie_score, dtype: bool

In [13]:
df['Gender'].notnull()

0     True
1    False
2     True
3     True
4     True
Name: Gender, dtype: bool

In [14]:
df[(df['pre_movie_score'].isnull()) & (df['Gender'].notnull())]

  first_name last_name   age Gender  pre_movie_score  post_movie_score
2      Stark      Mike  48.0      m              NaN               NaN

In [15]:
df.isna().sum()

first_name          1
last_name           1
age                 1
Gender              1
pre_movie_score     2
post_movie_score    2
dtype: int64

In [16]:
df.isna().sum().sum()

np.int64(8)

In [17]:
df.dropna()

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [18]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [19]:
df.dropna(thresh=1)

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [20]:
df.dropna(thresh=2)

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [21]:
df.dropna(thresh=5)

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [22]:
df.dropna(thresh=4,axis=1)

  first_name last_name   age Gender
0       Root      Joss  36.0      m
1        NaN       NaN   NaN    NaN
2      Stark      Mike  48.0      m
3      Sofie    Miller  39.0      f
4       Emma       Roy  84.0      f

In [23]:
df.fillna('NEW')

  first_name last_name   age Gender pre_movie_score post_movie_score
0       Root      Joss  36.0      m             8.0              9.0
1        NEW       NEW   NEW    NEW             NEW              NEW
2      Stark      Mike  48.0      m             NEW              NEW
3      Sofie    Miller  39.0      f             7.0              8.0
4       Emma       Roy  84.0      f             6.0              8.0

In [24]:
df['first_name'].fillna('BLANK')

0     Root
1    BLANK
2    Stark
3    Sofie
4     Emma
Name: first_name, dtype: object

In [25]:
df.fillna(df['pre_movie_score'].mean())

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        7.0       7.0   7.0    7.0              7.0               7.0
2      Stark      Mike  48.0      m              7.0               7.0
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [26]:
df['pre_movie_score'].mode()

0    6.0
1    7.0
2    8.0
Name: pre_movie_score, dtype: float64

In [27]:
df['pre_movie_score'].median()

np.float64(7.0)

In [28]:
df1=pd.read_csv("C:\\Users\\cl601_07\\Documents\\24070127070\\Dataset\\Students_expenses.csv")

In [29]:
df1

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0     NaN  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500     NaN  9100.0  7800.0
5      June  9200  7100.0  8850.0     NaN

In [30]:
df1.columns

Index(['Expenses', 'Riya', 'Samual', 'Neeti', 'Shreya'], dtype='object')

In [31]:
df1.fillna(df1.mean())

TypeError: Could not convert ['JanuaryFebruaryMarchAprilMayJune'] to numeric

In [ ]:
df1.fillna(df1[['Riya', 'Samual', 'Neeti', 'Shreya']].mean())

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  8970.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  6820.0  9100.0  7800.0
5      June  9200  7100.0  8850.0  7750.0

In [32]:
df1.fillna(df1[['Riya', 'Samual', 'Neeti', 'Shreya']].median())

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  8900.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  7100.0  9100.0  7800.0
5      June  9200  7100.0  8850.0  7800.0

In [33]:
df1.fillna(df1[['Riya', 'Samual', 'Neeti', 'Shreya']].mode())

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  8850.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  7500.0  9100.0  7800.0
5      June  9200  7100.0  8850.0     NaN

In [34]:
df1.fillna(df1[['Riya', 'Samual', 'Neeti', 'Shreya']].min())

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  8800.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  6100.0  9100.0  7800.0
5      June  9200  7100.0  8850.0  7200.0

In [35]:
df1.fillna(df1[['Riya', 'Samual', 'Neeti', 'Shreya']].max())

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  9200.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  7500.0  9100.0  7800.0
5      June  9200  7100.0  8850.0  8150.0

In [36]:
dict={'Maths':[85,91,np.nan,91],'Chemistry':[72,75,74,np.nan],'Physics':[np.nan,68,82,81],'Biology':[81,81,72,np.nan]}

In [37]:
Before_imputation=pd.DataFrame(dict)

In [38]:
Before_imputation

   Maths  Chemistry  Physics  Biology
0   85.0       72.0      NaN     81.0
1   91.0       75.0     68.0     81.0
2    NaN       74.0     82.0     72.0
3   91.0        NaN     81.0      NaN

In [42]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
After_imputation=imputer.fit_transform(Before_imputation)
After_imputation

array([[85. , 72. , 74.5, 81. ],
       [91. , 75. , 68. , 81. ],
       [88. , 74. , 82. , 72. ],
       [91. , 73. , 81. , 76.5]])

In [43]:
After_imputation=pd.DataFrame(After_imputation,columns=['Maths','Chemistry','Physics','Biology'])
After_imputation

   Maths  Chemistry  Physics  Biology
0   85.0       72.0     74.5     81.0
1   91.0       75.0     68.0     81.0
2   88.0       74.0     82.0     72.0
3   91.0       73.0     81.0     76.5