In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Create dataframe using dictionary aproach

In [ ]:
diction={'Country':['India','US','Japan','India','China','Japan'],'AGE':[35,28,31,38,30,34],'Salary':[48000,42000,46000,52000,60000,64000]}
frame=pd.DataFrame(diction)
frame

  Country  AGE  Salary
0   India   35   48000
1      US   28   42000
2   Japan   31   46000
3   India   38   52000
4   China   30   60000
5   Japan   34   64000

In [ ]:
frame.dtypes

Country    object
AGE         int64
Salary      int64
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_enco=LabelEncoder()

In [ ]:
z=frame.Country.unique()
frame["Country"].unique()

array(['India', 'US', 'Japan', 'China'], dtype=object)

In [ ]:
len(z)

4

In [ ]:
frame['Country_label']=label_enco.fit_transform(frame['Country'])
frame

  Country  AGE  Salary  Country_label
0   India   35   48000              1
1      US   28   42000              3
2   Japan   31   46000              2
3   India   38   52000              1
4   China   30   60000              0
5   Japan   34   64000              2

In [ ]:
frame_2=frame.drop(columns=['Country'])
frame_2

   AGE  Salary  Country_label
0   35   48000              1
1   28   42000              3
2   31   46000              2
3   38   52000              1
4   30   60000              0
5   34   64000              2

In [ ]:
from sklearn.preprocessing import OneHotEncoder
OHenco=OneHotEncoder()

In [ ]:
frame.Country.shape

(6,)

In [ ]:
frame.Country.ndim

1

In [ ]:
frame.Country.values.reshape(-1,1)

array([['India'],
       ['US'],
       ['Japan'],
       ['India'],
       ['China'],
       ['Japan']], dtype=object)

In [ ]:
frame.Country.values.reshape(-1,1).ndim

2

In [ ]:
Z=OHenco.fit_transform(frame.Country.values.reshape(-1,1)).toarray()
Z

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
frame_1=pd.DataFrame(Z,columns=['Country_'+str(int(i)) for i in range(Z.shape[1])])
frame_1

   Country_0  Country_1  Country_2  Country_3
0        0.0        1.0        0.0        0.0
1        0.0        0.0        0.0        1.0
2        0.0        0.0        1.0        0.0
3        0.0        1.0        0.0        0.0
4        1.0        0.0        0.0        0.0
5        0.0        0.0        1.0        0.0

In [ ]:
frame_1_up=pd.concat([frame_1,frame],axis=1)
frame_1_up

,Country_0,Country_1,Country_2,Country_3,Country,AGE,Salary,Country_label
0,0.0,1.0,0.0,0.0,India,35,48000,1
1,0.0,0.0,0.0,1.0,US,28,42000,3
2,0.0,0.0,1.0,0.0,Japan,31,46000,2
3,0.0,1.0,0.0,0.0,India,38,52000,1
4,1.0,0.0,0.0,0.0,China,30,60000,0
5,0.0,0.0,1.0,0.0,Japan,34,64000,2

In [ ]:
frame_1_up.drop(columns='Country',inplace=True)
frame_1_up

   Country_0  Country_1  Country_2  Country_3  AGE  Salary  Country_label
0        0.0        1.0        0.0        0.0   35   48000              1
1        0.0        0.0        0.0        1.0   28   42000              3
2        0.0        0.0        1.0        0.0   31   46000              2
3        0.0        1.0        0.0        0.0   38   52000              1
4        1.0        0.0        0.0        0.0   30   60000              0
5        0.0        0.0        1.0        0.0   34   64000              2

not TASK

In [ ]:
df=pd.read_csv("C:\\Users\\cl601_07\\Documents\\24070127070\\Dataset\\Encoding_data (1).csv")
df

   Sr. No GENDER  AGE MARITAL_STATUS    PROFESSION
0       0      M   27         Single  Professional
1       1      F   39        Married         Other
2       2      F   39        Married         Other
3       3      F   56    Unspecified   Hospitality
4       4      M   45        Married       Retired

In [ ]:
df.drop(columns=['Sr. No'],inplace=True)
df.columns

Index(['GENDER', 'AGE', 'MARITAL_STATUS', 'PROFESSION'], dtype='object')

In [ ]:
df_dum=pd.get_dummies(df,columns=[ 'GENDER', 'MARITAL_STATUS', 'PROFESSION'])
df_dum=df_dum.astype(int)
df_dum

,AGE,GENDER_F,GENDER_M,MARITAL_STATUS_Married,MARITAL_STATUS_Single,MARITAL_STATUS_Unspecified,PROFESSION_Hospitality,PROFESSION_Other,PROFESSION_Professional,PROFESSION_Retired
0,27,0,1,0,1,0,0,0,1,0
1,39,1,0,1,0,0,0,1,0,0
2,39,1,0,1,0,0,0,1,0,0
3,56,1,0,0,0,1,1,0,0,0
4,45,0,1,1,0,0,0,0,0,1